config/routes.rb
Rails.application.routes.draw do
  get 'leads/new'

    root 'welcome#index'

    get 'schools' => 'welcome#schools'
    get 'programs' => 'welcome#programs'
    get 'welcome/schools'
    get 'welcome/teachers'
    get 'welcome/faq'
    
    resources :leads, only: [:create]
  
  get 'sitemap.xml' => 'sitemap#sitemap'

end

app/models/contact.rb
# Simple model to handle validation
class Contact
  include ActiveModel::Validations
  attr_accessor :phone
  validates_presence_of :phone
  validates :phone, :phony_plausible => true
end

app/models/lead.rb
class Lead < ActiveRecord::Base
    before_save {self.email = email.downcase}
    validates :name, presence: true
    validates :phone, :presence => {:message => "can't be blank, unless email is present."}, unless: -> (lead){lead.email.present?}
    validates :email, :presence => {:message => "can't be blank, unless phone is present."}, unless: -> (lead){lead.phone.present?}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, format: { with: VALID_EMAIL_REGEX}, :allow_blank => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
    
    def create
        @lead = Lead.new(lead_params)
        
        if @lead.save
            # Handle goos save.
            flash[:success] = "Thanks for your message. \n We will get back with you as soon as possible."
            lead_email(@lead)
            redirect_to root_path
        else
            # Problem with saving.
            flash[:danger] = "Something went wrong on your request. Try again with some changes in your data."
            render 'welcome/index'
        end
    end
    
    private
    
    def lead_params
        params.require(:lead).permit(:name, :email, :phone, :message)
    end
    
    def lead_email(lead)
        if params[:lead][:email].blank?
            #what to do if email is blank
        else
            #what to do if email is present
            LeadMailer.welcome_to_new_lead_email(lead).deliver_now!
            LeadMailer.notify_about_new_lead(lead).deliver_now!
        end 
    end
    
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  @@domain = "www.codebyme.com"

  def sitemap
    render inline: static_sitemap.render
  end

  #This method will render a static sitemap while the dynamic method is working.
  def static_sitemap
    map = XmlSitemap::Map.new(@@domain) do |m|
      # Available :period -> :none :always :hourly :daily :weekly :monthly :yearly :never
      m.add welcome_schools_path, :priority => 0.8, :updated => Date.today, :period => :weekly
      m.add welcome_teachers_path, :priority => 0.6, :updated => Date.today - 1.day
      m.add welcome_faq_path, :priority => 0.3
    end
    return map
  end

  #This method will create a sitemap with all the valid routes in this application
  #TODO: Figure out how to filter out the routes that we don't want google to crawl.
  def dynamic_sitemap
    map = XmlSitemap::Map.new(@@domain) do |m|
      paths = ApplicationHelper::RouteRecognizer.new.initial_path_segments
      paths.each { |path| m.add path}
    end
  end

end

app/controllers/twilio_controller.rb
require 'twilio-ruby'

class TwilioController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  # Before we allow the incoming request to connect, verify
  # that it is a Twilio request
  before_filter :authenticate_twilio_request, :only => [ :connect ]

  # Define our Twilio credentials as instance variables for later use
  @@twilio_sid = ENV['TWILIO_ACCOUNT_SID']
  @@twilio_token = ENV['TWILIO_AUTH_TOKEN']
  @@twilio_number = ENV['TWILIO_NUMBER']

  # Render home page
  def index
  	render 'index'
  end

  # Handle a POST from our web form and connect a call via REST API
  def call
    contact = Contact.new
    contact.phone = params[:phone]

    # Validate contact
    if contact.valid?

      @client = Twilio::REST::Client.new @@twilio_sid, @@twilio_token
      # Connect an outbound call to the number submitted
      @call = @client.calls.create(
        :from => @@twilio_number,
        :to => contact.phone,
        :url => "#{root_url}connect" # Fetch instructions from this URL when the call connects
      )

      # Lets respond to the ajax call with some positive reinforcement
      @msg = { :message => 'Phone call incoming!', :status => 'ok' }

    else

      # Oops there was an error, lets return the validation errors
      @msg = { :message => contact.errors.full_messages, :status => 'ok' }
    end
    respond_to do |format|
      format.json { render :json => @msg }
    end
  end

  # This URL contains instructions for the call that is connected with a lead
  # that is using the web form.  These instructions are used either for a
  # direct call to our Twilio number (the mobile use case) or
  def connect
    # Our response to this request will be an XML document in the "TwiML"
    # format. Our Ruby library provides a helper for generating one
    # of these documents
    response = Twilio::TwiML::Response.new do |r|
      #r.Say 'If this were a real click to call implementation, you would be connected to an agent at this point.', :voice => 'alice'
      r.Dial "+17872420390"
    end
    render text: response.text
  end


  # Authenticate that all requests to our public-facing TwiML pages are
  # coming from Twilio. Adapted from the example at
  # http://twilio-ruby.readthedocs.org/en/latest/usage/validation.html
  # Read more on Twilio Security at https://www.twilio.com/docs/security
  private
  def authenticate_twilio_request
    twilio_signature = request.headers['HTTP_X_TWILIO_SIGNATURE']

    # Helper from twilio-ruby to validate requests.
    @validator = Twilio::Util::RequestValidator.new(@@twilio_token)

    # the POST variables attached to the request (eg "From", "To")
    # Twilio requests only accept lowercase letters. So scrub here:
    post_vars = params.reject {|k, v| k.downcase == k}

    is_twilio_req = @validator.validate(request.url, post_vars, twilio_signature)

    unless is_twilio_req
      render :xml => (Twilio::TwiML::Response.new {|r| r.Hangup}).text, :status => :unauthorized
      false
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @lead = Lead.new
    end
    
    def schools
    end
    
    def teachers
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
    # If title is empty it returnsa default title for all pages.
    def full_title(page_title = '')
        base_title = "Providing a Fun Learning environment for Young Coders and Creators in Orlando, FL"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end

    class RouteRecognizer
    attr_reader :paths

    # To use this inside your app, call:
    # `RouteRecognizer.new.initial_path_segments`
    # This returns an array, e.g.: ['assets','blog','team','faq','users']

      #This regular expression will match url without special characters or parameters
      INITIAL_SEGMENT_REGEX = %r{^\/([^(:]+)}

    def initialize
      routes = Rails.application.routes.routes
      @paths = routes.collect {|r| r.path.spec.to_s }
    end

    def initial_path_segments
      @initial_path_segments ||= begin
        paths.collect {|path| match_initial_path_segment(path)}.compact.uniq
      end
    end

    def match_initial_path_segment(path)
      if match = INITIAL_SEGMENT_REGEX.match(path)
        match[1]
      end
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_analyticstracking.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-54TFJT"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-54TFJT');</script>
<!-- End Google Tag Manager -->

app/views/layouts/_facebooksdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '153602158333766',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/analyticstracking" %>
  <%= render "layouts/facebooksdk" %>
        <header class="header-20 navbar-fixed-top" id="top" role="navigation">
            <div class="container">
            <% flash.each do |message_type, message| %>
            <div class="container main-error">
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            </div>
            <% end %>
                <div class="row">
                    <div class="navbar col-sm-12" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle"></button>
                             <%= link_to(image_tag(asset_path("20151010 - codebyme logo.png"), size: "230x132", alt: "Code by Me"), root_path, class: "brand") %>
                          <div class="navbar brand">
                      <a id="socialpopover" tabindex="0" class="btn btn-sm navbar-btn" role="button"  data-placement="bottom"
                               data-html="true" title="Social Options">
                              <div role="navigation" class="fui-facebook navbar-btn"></div>
                                </a>
                      </div>
                        </div>

                        <div class="navbar-collapse collapse pull-right">
                            <ul class="nav">
                              <%= render "shared/nav_links" %>
                            </ul>
                          <!-- The content below is the facebook like icon - to be shown as a popover -->
                          <div id="popoverHiddenContent" style="display: none" class='fb-like' data-layout='button' data-action='like' data-show-faces='false' data-share='false'></div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="header-background"></div>
        </header>

    <%= yield %>

        <footer class="footer-12" id="section4">
            <div class="container">Start creating with CodebyMe.com</div>
            <div class="additional">
            With <span class="fui-heart"> </span> from Orlando, Florida
            </div>
        </footer>

        <footer class="footer-2 bg-midnight-blue" id="section5">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li class="active"><a href="#top">Take me Up</a></li>
                        <%= render "shared/nav_links" %>
                    </ul>
                </nav>
                <div class="social-btns pull-right">
                    <%= render "shared/social_links" %>
                </div>
            </div>
        </footer>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/leads/new.html.erb
<h1>Leads#new</h1>
<p>Find me in app/views/leads/new.html.erb</p>

app/views/shared/_contacts.html.erb
<section class="contacts-1" id="contactus">
    <div class="container">
    <div class="row">
        <div class="col-sm-8">
            <h3>We love what we do. <br> Let us tell you why you will too.</h3>
            <%= render 'shared/error_messages' %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <%= form_for(@lead) do |f| %>
            <%= f.label :label, "Name / Last Name", class: "h6" %>
            <%= f.text_field :name, class:"form-control" %>
                <%= label(:lead, :email, "E-mail", class:"h6") %>
                <%= email_field(:lead,:email, class: "form-control") %>
                <%= label(:lead, :phone, "Phone", class:"h6") %>
                <%= telephone_field(:lead,:phone, class: "form-control") %>
                <%= label(:lead, :message, "Message", class:"h6") %>
                <%= text_area(:lead, :message, rows: 7, class:"form-control") %>
                <%= button_tag(type: 'submit',class: "btn btn-primary") do %>
                    <span class="fui-mail"></span>
                <% end %>
            <% end %>
        </div>
        
        <div class="col-sm-4 col-sm-offset-1">
            <div class="additional">
                <h6>Need Help?</h6>
                <p>Don’t hestiate to ask us something. Email us directly <%= image_tag("infoatcodebyme.png", size: "150" , alt: "Email to communicate") %> or call us at <b>407-901-2555</b>. You can checkout our <a href="<%= welcome_faq_path %>">FAQ</a> page to get more information about our service.</p>
            </div>
            <div class="additional">
                <h6>Some Facts</h6>
                <p>Every student in every school should have the opportunity to learn computer science.</p>
                <p>There are currently over 500k open computing jobs nationwide.</p>
            </div>
            <div class="phone">
                <big>407-901-2555</big>
                AVAILABLE ANYTIME
            </div>
        </div>
    </div>
    </div>
</section>

app/views/shared/_error_messages.html.erb
<% if @lead.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(@lead.errors.count, "error") %>.
    </div>
    <ul>
        <% @lead.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav_links.html.erb
<%= active_link_to 'For Parents', root_path, :active => :exclusive, :wrap_tag => :li %>
<%= active_link_to 'For Schools', welcome_schools_path, :wrap_tag => :li %>
<%= active_link_to 'For Teachers', welcome_teachers_path, :wrap_tag => :li %>
<%= active_link_to 'Contact Us', root_path + "#contactus", :active => :false, :wrap_tag => :li %>

app/views/shared/_quotes.html.erb
<section class="content-18">
    <div class="background">&nbsp;</div>
    <div class="container">
        <div id="c-18_myCarousel" class="carousel slide" data-interval="600000">
            <div class="controls">
                <a class="carousel-control left disabled" href="#" data-slide="prev"> </a>
                <a class="carousel-control right" href="#c-18_myCarousel" data-slide="next"> </a>
            </div>
            <div class="carousel-inner">
                <div class="item active">
                    <div class="quote-text">
                        Don't Just play on your phone, program it.
                    </div>
                    <div class="quote-author">@Obama, President Obama</div>
                </div>
                <div class="item">
                    <div class="quote-text">
                        If you can change technology, you can change the world.
                    </div>
                    <div class="quote-author">Unknonwn</div>
                </div>
                <div class="item">
                    <div class="quote-text">
                        Everybody in this country should learn how to program a computer... because it teaches you how to think.
                    </div>
                    <div class="quote-author">Steve Jobs</div>
                </div>
            </div>
        </div>
<!--         <div class="row quotes">
            <div class="col-sm-3">
                <h6>@mc</h6>
                Easy to change and easy to create new elements with color.
            </div>
            <div class="col-sm-4 col-sm-offset-1">
                <h6>@madbyte</h6>
                Awesome Kit. It’s more easiest way to make my startup. Thanks!
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <h6>@stSilent</h6>
                Create new elements with color swatches. Wow!
            </div>
        </div> -->
    </div>
</section>

app/views/shared/_social_links.html.erb
<!-- <a href="#">
    <div class="fui-vimeo"></div>
    <div class="fui-vimeo"></div>
</a> -->
<a href="https://www.facebook.com/codingbyme/">
    <div class="fui-facebook"></div>
    <div class="fui-facebook"></div>
</a>
<!-- <a href="#">
    <div class="fui-twitter"></div>
    <div class="fui-twitter"></div>
</a>
 -->

app/views/twilio/index.erb
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title>Click To Call Tutorial</title>
    <link rel="icon" type="image/png" href="/img/favicon.png">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" type="text/css">
    <%= stylesheet_link_tag 'application' %>
  </head>
  <body>
    <div class="container">
      <h1>Click To Call</h1>
      <p>Click To Call converts your website's users into engaged customers by creating an easy way for your customers to contact your sales and support teams right on your website.</p>
      <p>Here's an example of how it's done!</p>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <form id="contactform" role="form" action="#" method="POST">
            <div class="form-group">
              <h3>Call Sales</h3>
              <p class="help-block">
                Are you interested in impressing your friends and confounding your enemies? Enter your phone number below, and our team will contact you right away.
              </p>
            </div>
            <div class="form-group">
              <input class="form-control" type="text" name="phone" id="phoneNumber" placeholder="(651) 555-7889">
            </div>
            <button type="submit" class="btn btn-default">Contact Sales</button>
          </form>

        </div>
      </div>
	  </div><!-- /page -->
	</body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/twilio/index.haml
!!!  
%html  
  %head  
    %title Click To Call Tutorial
    %link{:rel => "icon", :type => "image/png", :href => "/img/favicon.png"}
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"}
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css", :type => "text/css"}
    = stylesheet_link_tag 'application', :media => 'all'
    
  %body
    .container
      %h1 Click To Call
      %p
        Click To Call converts your website's users into engaged customers by creating an easy way for your customers to contact your sales and support teams right on your website.

      %p Here's an example of how it's done!

      %hr

      // C2C contact form
      .row
        .col-md-12
          %form{:id => "contactform", :role => 'form', :action => '#', :method => 'POST'}
            .form-group
              %h3 Call Sales
              %p.help-block
                Are you interested in impressing your friends and confounding your enemies? Enter your phone number below, and our team will contact you right away.
            .form-group
              %input.form-control{:type =>'text', :name => 'phone', :id => 'phoneNumber', :placeholder => '(651) 555-7889'}
            %button{ :type => 'submit', :class => 'btn btn-default'} Contact Sales
            
  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/welcome/faq.html.erb
<section class="content-29">
    <div class="container">
        <div class="col-sm-8 col-sm-offset-2">
            <h3>Code by Me Frequently Asked Questions</h3>
            <p>This section will help answer a few of the basic questions. Keep visiting this section since we will be updating this section constantly.</p>
        </div>
        <div class="player">
            <iframe id="pPlayer" width="853" height="480" src="https://www.youtube.com/embed/qYZF6oIZtfc?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
        </div>
        
        <div class="row features">
            <div class="col-sm-3">
                <%= image_tag("pencil-ruler-icon.png", size:"100", alt:"pencil and ruler") %>
                <h6>What we do?</h6>
                We teach children problem solving skills with the use of programming coding. We have a rich curriculum that makes it fun and engaging for children. 
            </div>
            <div class="col-sm-4 col-sm-offset-1">
                <%= image_tag("desktop-icon.png", size:"100", alt:"pencil and ruler") %>
                <h6>Where we located?</h6>
                Currently all our classes are offered through schools in different areas of Orlando FL. 
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <%= image_tag("graph-icon.png", size:"100", alt:"pencil and ruler") %>
                <h6>Why should you care?</h6>
                In less than 10 years, there will be 1 Million computer coding jobs more than students to fill them. Even if your kids select another field of study for college, we think is important that everyone has the skills develop with computer coding.
            </div>
        </div>
    </div>
</section>

app/views/welcome/index.html.erb
<% provide(:title, "For Parents") %>

   <header id="parents" class="header-4 v-center bg-midnight-blue">
    <div class="background parents">&nbsp;</div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="hero-unit">
                        <h1>Image it, <br> Learn to Code, <br> Create it!</h1>
                        <p class="lead">We go to your school and teach kids coding.</p>
                    </div>
                    <div class="btns">
                      <a class="btn btn-info" href="#How">Learn How <span class="glyphicon glyphicon-play"> </span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

    <section class="content-5" id="How">
        <div class="container">
          <div class="feature-image" >
            <%= image_tag("long-arms-robot.png", class:"feature-image", style:"position:relative;") %>
          </div>
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <h3>How we create creators?  <a class="feature-image btn btn-info" href="javascript:;"><span class="feature-image glyphicon glyphicon-play"></span></a></h3>
                    <p class="lead">We are a group of technologists and educators that teach children computer coding to develop problem solving and critical thinking skills. Coding empowers students and gives them tools to express themselves in very creative ways.</p>
                </div>
            </div>
            <div class="row features">
                <div class="col-sm-4 col-sm-offset-2">
                  <span class="fui-"><%= image_tag("bracket-code-icon.png") %> </span>
                    <h6>Afterschool Programs</h6>
                    <p>Let us come to your school! We provide the instructors, the technology and interactive content; all the schools need to provide is the learning space and the students eager to learn and create.</p>
                  <%= link_to("Learn More",programs_path + "#afterschoolprograms", class: "feature link") %>
                </div>
                <div class="col-sm-4 col-sm-offset-1">
                    <span class="fui-"><%= image_tag("browser-finger-icon.png") %> </span>
                    <h6>Summer Camps</h6>
                    <p>Summer camps designed for girls and boys between the ages of 7 and 13. These kids will come out wanting to become builders and makers of technology. Week long and full day sessions available.</p>
                  <%= link_to("Learn More",programs_path + "#summercamps", class: "feature link") %>
                </div>
            </div>
            <div class="row features">
                <div class="col-sm-4 col-sm-offset-2">
                  <span class="fui-"><%= image_tag("browser-icon.png") %> </span>
                    <h6>Hour of Code</h6>
                    <p>The Hour of Code is a one-hour introduction to computer science workshop, designed to expose kids to coding and show that anybody can learn the basics. This will take place December 7 - 13 in celebration of Computer Science Education Week. Join us, it’s free!</p>
                  <%= link_to("Learn More",programs_path + "#hourofcode",class: "feature link") %>
                </div>
                <div class="col-sm-4 col-sm-offset-1">
                  <span class="fui-"><%= image_tag("cloud-icon.png") %> </span>
                    <h6>Weekend Camps</h6>
                    <p>In 2016 we’re offering weekend camps. Bring your child Saturday and Sunday for an all day workshop focused on computer coding.</p>
                </div>
            </div>
        </div>
    </section>

<%= render "shared/quotes" %>

    <section class="content-4" id="section3">
        <div class="container">
        <h3>What is different about our program?</h3>
        <div class="row features">
            <div class="col-sm-4">
                <%= image_tag("pencil-ruler-icon.png", size:"100", alt:"pencil and ruler") %>
                <h6>About Us</h6>
                <p>We are a team of husband and wife who share the passion for technology and education. Together we are creating opportunities for kids to learn computer coding, a new type of literacy that will be very necessary in their future</p>
            </div>
            <div class="col-sm-4">
                <img src="<%= asset_path("common-files/icons/rocket@2x.png") %>" alt="" width="101" height="101">
                <h6>Our Mission</h6>
                <p>We have the mission to lead youth in becoming passionate builders - not just consumers - of technology by learning computer coding and technical skills in a hands-on, social, and collaborative way.</p>
            </div>
            <div class="col-sm-4">
                <%= image_tag("desktop-icon.png", size:"100", alt:"pencil and ruler") %>
                <h6>What's different?</h6>
                <p>Our varied curriculum teaches computer coding using different resources. We have a welcoming environment where beginners of all backgrounds can come together to learn essential 21st century technical skills.</p>
            </div>
        </div>
        </div>
    </section>

    <%= render "shared/contacts" %>

app/views/welcome/programs.html.erb
<% provide(:title, "Kid Programs for Learning Coding") %>


<section class="content-31">
    <div class="container">
        <div class="row" id="afterschoolprogram">
            <div class="number">1</div>
            <div class="col-sm-8 col-sm-offset-2" >
                <h3>After School Programs</h3>
                <p>Our program is currently offered in various schools in the Orlando vicinity. We provide schools with certified teachers, the curriculum and the technology to offer our program at your school. The enrollment process is easy and can be done directly with us.</p>
                <div class="box">
                    <div class="img">
                      <%= image_tag("coding-projects-for-kids-with-blockly-app-wonder-workshop_zpsxzwnjuso.png", size: "380x187", alt: "Girl with Block Codes") %>
                      <%= image_tag("coding-projects-for-kids-with-blockly-app-wonder-workshop_zpsxzwnjuso.png", size: "380x187", alt: "Girl with Block Codes") %>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" id="summercamps">
            <div class="number">2</div>
            <div class="col-sm-8 col-sm-offset-2" >
                        <h3>Summer Camps</h3>
                        <p>We offer week-long summer camps, in which your kid will have fun while learning computer coding, robotics and game design. To receive an early sign-up discount, please contact us at <%= link_to(image_tag("infoatcodebyme.png", size: "150" , alt: "Email to communicate"), root_path + "#contactus") %>.</p>
                        <div class="box">
                            <div class="img">
                              <%= image_tag("children_learning_coding_during_summer.jpg", size: "640x218", alt: "Children Playing in Orlando FL") %>
                              <%= image_tag("children_learning_coding_during_summer.jpg", size: "640x218", alt: "Children Playing in Orlando FL") %>
                            </div>
                        </div>
          </div>
      </div>

        <div class="row" id="hourofcode">
            <div class="number">3</div>
            <div class="col-sm-8 col-sm-offset-2">
                <div id="pt-2" class="page-transitions pt-perspective pt-item-1 pt-first">
                        <h3>Hour of Code</h3>
                        <p>During the week of December 7 through 13, we celebrate the computer science week. We will take part by hosting the hour of code. Also, throughout the year we offer hour long workshops for children to explore our curriculm and fun activities.</p>
                        <div class="box">
                            <div class="img">
                              <%= image_tag("zuckerberg_poster-2013.png", size: "397x193") %>
                              <%= image_tag("zuckerberg_poster-2013.png", size: "397x193") %>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>